### ISSUE TITLE
Pipeline functionality with 3d step?

### ISSUE THREAD

**Issue by kenjdavidson** [OrganicaWild/OrganicaWild#22]
Came across this when looking for libraries for a small project I want to work on.  I'm pretty new to Unity and obviously this looks like a great choice.  I'm curious that if I get things working in the 2d world, if it would be easy enough to add in a 3d step to give the  generated areas/meshes a height?

For example:
- adding mountains around the edges
- rivers along some of the area connections
- etc

or if this would require more additions/implementations of what there is now?  Or if this just isn't possible given that the WorldMap drawing is entirely 2d based?

**Comment by cvoegele** [comment]
Hi! Thank you for checking out my little library here. So exciting that someone wants to use this code!

Depending on what you are trying to-do with 3d, it's definitely possible! Currently, what it supports is to use 3d objects (or any sort of objects) in the recipes that instantiate the 2d shapes after the pipeline is run. 
In the example I provide for the forest level, you can also see that the trees and stones are just 3d models. 

So if, for example, you wanted to add a mountain range around the edges (of the areas? Or map?) I suppose you could use a new recipe that does this with the area.
I could however see how that can be quite complex with the current setup. 

> I'm curious that if I get things working in the 2d world, if it would be easy enough to add in a 3d step to give the generated areas/meshes a height?

The generated meshes right now are just a flat plane, if it would need more code to make a 3d mesh, as the mesh would need side panels and a floor. You can see the AreaMeshRecipe Code is the one that is used to create the flat planes https://github.com/OrganicaWild/OrganicaWild/blob/master/Framework/Pipeline/Standard/ThemeApplicator/Recipe/AreaMeshRecipe.cs 
It would need some sort of Recipe which, instead of transforming the 2d polygon into a flat plane, transforming it into a 3d mesh with height.
However, the library doesn't really provide functionality for creating 3d meshes right now.

Maybe you could provide a little sketch on what you are trying to achieve specifically, as right now I am just kind of guessing. I would love to help you!

**Comment by kenjdavidson** [comment]
Essentially I'm just looking for a project to get me doing something in Unity.   I had two goals:

1. Create a vanilla proc gen mini putt game to play with my son.   The library looks perfect for that, as it would be:
- Generating areas
- Picking a couple joined areas
- placing walls on the edges
- placing a "hole"
- placing some random objects

2. Once I got a little bit under my belt, I wanted to try a single hole, for something like a par 3 closest to the pin/hole in one competition.  Again the 2d portion is pretty straight forward:
- generate the areas
- pick an area for the green
- pick an are for the tee
- place the objects 

The last step of this would be to apply heights:
- pull edges down to make creeks
- raise edges up to make hills
- etc.

With regards to the recipes and the mesh creation, I think I have a basic handle on how to do this (obviously pulling it off will be different).  

The key class i see is `GameObjectCreation` where it mainly handles the flipping from Y to Z, which is static, so the usages cannot be injected.  This is (if I'm reading this properly) the one spot where it may get held up.

**Comment by cvoegele** [comment]
Ah, okay, I see. Cool that you are getting your hands on Unity. I like it and it can be very fun! I hope you can create cool things, like that putt game you are describing!

I am very confident that creating what you describe in point 1) and 2) is definitely possible with the pipeline.

And the generation in 3) could be done with the recipes. You would however have to code your own recipes.
I did a little sketch on what I would do. Maybe it can help you :) 

![Untitled_Artwork](https://github.com/OrganicaWild/OrganicaWild/assets/10659582/3c4086b9-d1ad-4790-be9c-839de5486c67)

As for the flipping, I just checked the code in the `GameObjectCreation` Class, and it looks like the flipping is not hard coded but actually configurable.

```c#
GameObjectCreation.YtoZ = true //default is false
GameObjectCreation.GetMeshesFromPolygon(polygon)
```

It's not a perfect interface. It is a bit state-machine like, but I think it can get the job done, for that specific parameter.

However, for creating these 3d meshes, the `GameObjectCreation` is probably not sophisticated enough. It would need some code, which would take this 2d polygon and creates a 3d mesh of some sort, which is not included in the library.

**Comment by kenjdavidson** [comment]
Right on thanks. I'll close this for now and maybe follow up with any specifics that come up when I get to building.
